// import type { Metadata } from "next";
// import { Inter, Playfair_Display } from "next/font/google";
// import "./globals.css";
// import { notFound } from "next/navigation";
// import Header from "./components/header/Header";
// import Footer from "./components/footer/Footer";
// import { ThemeProvider } from "./context/ThemeContext";


// const locales = ["uk", "en"];

// const inter = Inter({
//   subsets: ["latin"],
//   weight: ["300", "400", "500", "600"], // ті ваги, які тобі потрібні
// });

// const playfair = Playfair_Display({
//   subsets: ["latin"],
//   weight: ["400", "600", "700"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default async function RootLayout({
//   children,
//   params,
// }: {
//   children: React.ReactNode;
//   params: Promise<{ locale: string }>;
// }) {
//   // Розпаковуємо params як Promise
//   const { locale } = await params;

//   // Перевіряємо, чи локаль підтримується
//   if (!locales.includes(locale)) {
//     notFound();
//   }

//   return (
//     <html lang={locale}>
//       <body className={`${inter.className} ${playfair.className}`}>
//         {/* <ThemeProvider> */}
//           <Header params={{
//           locale: undefined
//         }} />
//           <main>{children}</main>
//           <Footer />
//         {/* </ThemeProvider> */}
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import "./globals.css";
import { notFound } from "next/navigation";
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";
import ScrollToTop from "./components/scrollToTop/ScrollToTop";

const locales = ["uk", "en"];

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "HARLIB | Financial Law Boutique",
  description: "Юридичний бутик для фінансового сектору.",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  // 1. Чекаємо на розпаковку params
  const { locale } = await params;

  // 2. Валідуємо мову
  if (!locales.includes(locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body className={`${inter.className} ${playfair.className}`}>
        {/* 👇 ТУТ ВИПРАВЛЕНО: передаємо реальну локаль, яку отримав Layout! */}
        <Header params={{ locale: locale as 'uk' | 'en' }} />

        <main>{children}</main>

        {/* 👇 Сюди теж передаємо, щоб футер знав, яку мову рендерити */}
        <Footer params={{ locale: locale as 'uk' | 'en' }} />
        <ScrollToTop/>
      </body>
    </html>
  );
}